apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prereq-pfs-sales
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pfs-sales
    server: 'https://kubernetes.default.svc'
  source:
    path: app-prerequisites/overlays/dc2/sales/platformfoundations
    repoURL: 'https://github.com/raviusit/k8s-argocd-apps.git'
    targetRevision: HEAD
  syncPolicy:
   automated:
     selfHeal: true
     prune: true
  project: default