apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfs-hello-kubernetes-prod-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: dc2/prod
    repoURL: "https://github.com/raviusit/hello-kubernetes-prod-config"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pfs-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  project: default
